[project]
authors = ["RenaudLN <renaudlaine31@gmail.com>"]
channels = ["conda-forge"]
description = "Routine tracker app"
name = "routine-tracker"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
default = { features = ["dev"], solve-group = "default" }
app = { solve-group = "default" }

[dependencies]
python = "3.12.*"
gunicorn = ">=23.0.0,<24"
slugify = ">=0.0.1,<0.0.2"

[pypi-dependencies]
surrealdb = ">=1.0.3, <2"
routine = { editable = true, path = "." }
dash = "<3"
dash-mantine-components = "<1"
dash-pydantic-form = ">=0.14.7,<1"
dash-auth = { version = ">=2.3.0, <3", extras = ["oidc"] }

[tasks]
serve = "gunicorn routine.app:server"

[feature.dev.dependencies]
ruff = "*"
pre-commit = "*"
ipykernel = ">=6.29.5,<7"
pixi-kernel = ">=0.6.1,<0.7"

[feature.dev.tasks]
lint = "pre-commit run --all-files"
dev = "python routine/app.py"

[feature.dev.pypi-dependencies]
python-dotenv = ">=1.0.1, <2"
