mantine_provider = "__mantine-provider"
scheme_switch = "__scheme-switch"
notifications_wrapper = "__notifications-wrapper"
past_wrapper = "__past-wrapper"
past_date_select = "__past-date-select"
client_timezone = "__client-timezone"
